kind: Deployment
apiVersion: apps/v1
metadata:
  name: whoami
  namespace: default
  labels:
    app: traefiklabs
    name: whoami
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefiklabs
      task: whoami
  template:
    metadata:
      labels:
        app: traefiklabs
        task: whoami
    spec:
      containers:
        - name: whoami
          image: traefik/whoami
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: whoami
  namespace: default
spec:
  ports:
    - name: http
      port: 80
  selector:
    app: traefiklabs
    task: whoami

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-wildcard-host-internal
  namespace: default
spec:
  ingressClassName: traefik-internal
  rules:
  - host: "internal-foo.bar.com"
    http:
      paths:
      - pathType: ImplementationSpecific
        path: "/bar"
        backend:
          service:
            name: whoami
            port:
              number: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-wildcard-host-external
  namespace: default
spec:
  ingressClassName: traefik-external
  rules:
  - host: "aa2d2cc8aa9864cc5978a604418ced61-383162271.us-east-2.elb.amazonaws.com"
    http:
      paths:
      - pathType: ImplementationSpecific
        path: "/bar"
        backend:
          service:
            name: whoami
            port:
              number: 80
