apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    - key: node.kubernetes.io/instance-type
      operator: In
      values: [ "t3a.medium", "t3a.large","t3.medium","t3.small"]
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot"]
  limits:
    resources:
      cpu: 1000
  provider:
    securityGroupSelector:
      Name: sandbox-node
    subnetSelector:
      karpenter.sh/discovery: sandbox
      Name: sandbox-private-*
    instanceProfile: KarpenterIamInstanceProfile
  ttlSecondsAfterEmpty: 30
  ttlSecondsUntilExpired: 1800
